require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - .git/**/*
    - .github/**/*
    - bin/**/*
    - gemfiles/**/vendor/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  
