require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  
