default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: wave_walker_development
  queue:
    <<: *default
    database: wave_walker_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: wave_walker_test

production:
  primary: &primary_production
    <<: *default
    database: wave_walker_production
    username: wave_walker
    password: <%= ENV["WAVE_WALKER_DATABASE_PASSWORD"] %>
  queue:
    <<: *primary_production
    database: wave_walker_production_queue
    migrations_paths: db/queue_migrate
