name: Test and deploy (only main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Rails App
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://root:root@localhost/wave_walker_test
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: wave_walker_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt install -y --no-install-recommends libvips

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Database Setup
        run: bundle exec rails db:schema:load

      - name: Run rubocop
        uses: reviewdog/action-rubocop@v2.14.0
        with:
          skip_install: true
          use_bundler: true

      - name: Run erb-lint
        run: bundle exec erblint --lint-all 

      - name: Run tests
        run: bin/rails test

      - name: Run tests
        run: bin/rails test:system
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy
      cancel-in-progress: false
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_push_flags: -f
          git_remote_url: ${{ secrets.DOKKU_GIT_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
